### ISSUE TITLE
Re-populating venvs

### ISSUE THREAD

**Issue by memilanuk** [wsvincent/djangoforbeginners#109]
I'm not sure if this is something I missed early on (can't find it if I did) or if it's an oversight in the setup of the new venv at the beginning of each of the first few chapters.

Somewhere in chapter 1, the text has us upgrade `pip` to eliminate the annoying (albeit harmless) warning about pip in the venv lagging behind whatever the current version is.  Then we install `black` and set it up to fix any minor formatting errors upon save.  All well and good.

But when we start chapter 2, and create a new venv... all of that is left behind.  Assuming we're pointing VS Code at the new/current venv that we just created... it no longer has `black`, and it no longer has an updated version of `pip`.   Same in chapters 3, 4 and 5.  

The text appears to be getting the reader used to the 'rinse-lather-repeat' process of setting up a new development environment every time we start a new project - create a new venv, install django, create a new project, create a new app, make the necessary boiler plate modifications to settings, models, urls, views, etc., migrate db changes, create new directories for templates and static files, etc. etc. etc.... but completely skips over the (apparent) need to upgrade/reinstall `pip` and `black` every time as well, or any occasional reminders to point the 'Python Interpreter' setting in the editor (assuming VS Code) at the current venv, rather than the base install.

Unless that *is* the intention... which then kind of begs the question "why bother with a venv"?

As I said at the beginning... it's entirely possible  - or *probable* - that I missed something early on regarding this.  If so, please point me in the right direction.

**Comment by wsvincent** [comment]
Hi @memilanuk,

I appreciate this feedback. Installing `black` should only be necessary once if it is installed globally and then accessible to VSCode. I guess if you install `black` within a dedicated virtual environment you'll need to do it each time.

On the `pip` upgrade, I could probably add the instruction to each chapter with a new project. The error message prompts the install and gives the command so I thought mentioning it once would be enough but perhaps I should be more explicit going forward. The challenge for me is that `pip` might not always be out of date depending upon when someone installs `pip` so it's hard for me to write something that is 100% accurate now and in the future. I'll consider adding the `pip upgrade` bit to additional chapters.

To the larger question of "why bother with a venv"... I think you're missing the fundamental reason for a venv, which is to isolate Python dependencies. Probably what is confusing--and which I should spell out more clearly in the book--is that some packages like `black` can be installed globally since they are used on every project. But when it comes to Django versions and related things, you ALWAYS want to pin dependencies so you don't have things randomly breaking.

I suspect that's the source of confusion here. But I do appreciate your perspective on confusion around the whole mess. Python is not great around installation and packaging and it's only through reader feedback like this that I can hopefully keep improving it and keeping it accurate.

**Comment by memilanuk** [comment]
Okay... maybe (probably) I misunderstood the 'correct' use of `black`.  For some reason I thought it was supposed to be installed in the first venv we set up, not on the global/system Python.  Going back and reviewing that section, it looks like that was my mistake.

Perhaps to avoid having to add more boiler plate at the start of each chapter, maybe put a reference in the initial section about possibly needing to add it to subsequent venvs?

As far as the question of "why bother with a venv?"... that was somewhat rhetorical, given the above.  I 'get' the reason for isolating the python environments between projects... but have experienced a *lot* of frustration with getting and keeping both the editor and the console pointed at the 'right' (and the *same*) interpreter.  I think I have it sorted out now, through some trial and error between Windows Power Shell and VS Code.

**Comment by wsvincent** [comment]
I STILL sometimes forget that I'm already logged into a venv for another project and just navigate to a new one and wonder why things don't work right. It's somewhat inevitable I guess but at least now I know to check the venv if things are funky. Usually I can do `pip freeze` to see what's in the local venv as a quick check.

I'm still mainly Mac based and so I've also had a few cases where I had to switch between PowerShell and VSCode when using the shell. It's not ideal but I think MSFT will sort it out eventually.

Thanks again for writing in. I'm going to close this issue for now but feel free to start another one if you have questions or just email me directly at will@wsvincent.com.
