### ISSUE TITLE
Secret key error following 'fly launch' on Chapter 17 (Deployment)

### ISSUE THREAD

**Issue by rhfink** [wsvincent/djangoforbeginners#186]
After editing .env and settings.py to include my secret key, when I attempt to deploy my app using 'fly launch', i get the following error:

A default SECRET_KEY was not detected in 'django_project/settings.py'!
A generated SECRET_KEY <OMITTED> was set on Dockerfile for building purposes.
Optionally, you can use django.core.management.utils.get_random_secret_key() to set the SECRET_KEY default value in your django_project/settings.py.

However, when i run the relevant lines of code from settings.py that call the Secret Key via the interactive Python shell, I am able to successfully print the secret key.

Does the settings.py file need to be updated to be compatible with fly.io's configuration?

**Comment by wsvincent** [comment]
Fly.io has changed around their `fly launch` command since the book came out. For some reason they did not pickup a secret key in your existing config and so they then set one automatically in the pre-generated Dockerfile. You can use either one but it should be present in the Dockerfile and out of Git source control.
