### ISSUE TITLE
Chapter 7 - ModuleNotFoundError

### ISSUE THREAD

**Issue by robermus-parm** [wsvincent/djangoforbeginners#56]
Hello,
after having imported 'whitenoise', running:
python manage.py collectstatic
the shell returned:
ModuleNotFoundError: No module named 'whitenoise'
I couldn't find where the problem is.
Could you help me please?
Thank you,
Roberto

**Comment by wsvincent** [comment]
Hi Roberto,

Whitenoise isn't in your environment for some reason. Stuff like this happens often where you think you've installed a package but it's not available for some reason. My own internal checklist is the following:

- is WhiteNoise in both the Pipfile and the Pipfile.lock?
- am I in the virtual environment, so the shell with Pipenv?
- is WhiteNoise added correctly to the settings.py file?

Likely the issue lies with one of these 3 things. Let me know how it goes!

-Will
