### ISSUE TITLE
Chapter 3: ERROR

### ISSUE THREAD

**Issue by CrimsonSIS** [wsvincent/djangoforbeginners#57]
I'm getting this error, following the book:

> File "/Users/cole/Desktop/pages/pages_project/settings.py", line 59, in <module>
>     'DIRS': [os.path.join(BASE_DIR, 'templates')],  # new
> NameError: name 'os' is not defined
> (pages) bash-3.2$

**Comment by CrimsonSIS** [comment]
CORRECTION: pages_project/urls.py:

> from django.contrib import admin
> from django.urls import path
> from django.conf.urls import include
> 
> urlpatterns = [
>     path('admin/', admin.site.urls),
>     path('', include('pages.urls')),  # new
> ]

**Comment by CrimsonSIS** [comment]
CORRECTION: settings.py:

> from pathlib import Path
> import os

**Comment by wsvincent** [comment]
Hi, It seems maybe you're on the 3.0 version of the book? For 3.1 when you create a new Django project, the settings.py file uses pathlib so you need the update as you note. 

I also changed to using `config` instead of `pages_project` which should be reflected in the code here, too.

I think that's the issue. Let me know if anything else comes up.

**Comment by CrimsonSIS** [comment]
Dear Mr. Vincent:

Thanks for getting back to me. I noticed there is a new edition of the text
just this morning.

Will obtain it shortly.

Best intro to Django yet!

Best,

Jerry Cole

:-)

**Comment by CrimsonSIS** [comment]
Dear Mr. Vincent:

The Kindle people allowed me to upgrade my 3.0 edition of your book to 3.1.
It was difficult, because if you own 3.0, it echos that you already have
the title in your library when you click on the 3.1 edition.

Here's a heads-up on a typo:

Chapter 5: Blog App In this chapter we willll build

Vincent, William S.. Django for Beginners: Build websites with Python and
Django (p. 86). WelcomeToCode. Kindle Edition.

Can you edit the text post-publication?

Best,

Jerry Cole

:-)

**Comment by CrimsonSIS** [comment]
Dear Mr. Vincent:

Here is another typo:


{% load static %}
<html>
<head>
  <title>Django blog</title>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
rel=
*"styleshee\t">*
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>

in Chapter 5.

Best,

Jerry Cole

:-)

**Comment by wsvincent** [comment]
Hi Jerry,

Noted. I've updated this typo for the next edition. Thank you for letting
me know!

-Will

**Comment by wsvincent** [comment]
Hi Jerry,

 I assume you mean the "/" added to "stylesheet" here. That is
auto-formatting by Kindle to indicate a line break; ie the text itself
continues and does not have that break. I'm working on an online-only
version of the book since for Kindle titles formatting code properly is
basically impossible. I've spent quite a lot of time on this and, as most
books do not have code, it is not a priority for Amazon it seems.

Thank you for spotting it. If you see any other typos or code issues,
please let me know!

-Will

**Comment by CrimsonSIS** [comment]
Hi William:

I obtained the newer edition of the book from Amazon at no charge. A
technical support person in the Philippines flipped a virtual switch and
the newer edition appeared as if by magic in my Library.

I did read it thoroughly and implemented all of the examples.

As a matter of fact, I referenced it just last night.

One issue. For static files, the following worked:

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

This did not:

# config/settings.py
STATIC_URL = '/static/'
STATICFILES_DIRS = [str(BASE_DIR.joinpath('static'))] # new
# Vincent, William S.. Django for Beginners: Build websites with Python and
Django (p. 99). WelcomeToCode. Kindle Edition.

I also had to back-step the version of Django in order to be able to edit
User fields. Found numerous references/fixes related to this on the
Internet.

I used to edit computer science textbooks for Mitchell & Brown and McGraw
Hill. I also grew up doing typesetting for my dad's advertising business.
So, can't help but notice these things.

I'm a stickler for grammar as well, though these Harvard kids are pretty
much on the ball.

Working through Django for APIs next. Will keep you posted. Keep up the
evangelizing! I do think Django is the greatest thing since jello.

Best,

Jerry

:-)
