### ISSUE TITLE
Suggestion for Chapter 3 - Explaining git push heroku master

### ISSUE THREAD

**Issue by sockduct** [wsvincent/djangoforbeginners#59]
Hi Will - please let me know if you would prefer not to receive suggestions or if you would like them sent somewhere else.

In Chapter 3, on page 51 you mention:
```
(pages) $ git push heroku master
```
"If we had just typed git push origin master, then the code would have been pushed to GitHub, not Heroku. Adding heroku to the command sends the code to Heroku. This is a little confusing the first few times."

I'm sure you know that the heroku CLI is just adding another remote.  As you know, you can see the remotes with:
```
git remote -v
```
I'm sure you're familiar with the Python motto of "Explicit is better than implicit" from import this.  It is more detail to show/explain remotes.  However, if you understand remotes, then you understand exactly what's going on with the git push to heroku.  It is a little more advanced - perhaps worth a footnote?  I defer to you...

**Comment by wsvincent** [comment]
Hi @sockduct, This is a very good point. I think worthy of a footnote or an extra sentence or two in the next update.

You are right that "explicit is better than implicit." And at the same time, when it comes to Git and a few other things, I largely provide a quick overview and say "trust me on this" because I don't have the time/space to cover everything. In this case, I think more description is worth it.

But if you're curious, the challenge of the book--and indeed all my teaching--is sorting out the hierarchy of explaining concepts. Computers are just abstractions all the way down and when I was first learning things, I found the engineering-minded default to always start at the lowest-level was confusing. It was all details with little context.

In any event, hearing from readers helps me tweak things. So I appreciate you taking the time to write in. And, of course, for also reading the book!
